### ISSUE TITLE
Pull request #5 broke old behavior with PGPOOL_ENABLED=0

### ISSUE THREAD

**Issue by abdullah-kasim** [sobrinho/heroku-buildpack-pgpool#6]
Pull request #5 broke the previous behavior with PGPOOL_ENABLED=0.

Previously, with PGPOOL_ENABLED, I am able to switch pgpool on and off without changing the Procfile.

However, now, with PGPOOL_ENABLED=0, I will get the following error if I try to run a dyno with `bin/start-pgpool` appended:

```
user@user-kubuntu-desktop:~$ heroku run bin/start-pgpool rails console -a some-app
Running bin/start-pgpool rails console on ⬢ some-app... up, run.2663 (Standard-1X)
2022/04/28 18:05:23 no such file or directory <---- I get this error
```

I'll get the same error when I check with `heroku logs --tail`

**Comment by sobrinho** [comment]
Would you try the https://github.com/code1br/heroku-buildpack-pgpool/pull/7?
